version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ticketera
      POSTGRES_PASSWORD: admin
    ports:
      - "5432"
  app:
    build: .
    environment:
      DB_NAME: ticketera
      DB_USER: postgres
      DB_PASS: admin
      DB_HOST: db
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./src:/ticketera/src
    depends_on:
      - db
